### ISSUE TITLE
docker matrix-commander failed

### ISSUE THREAD

**Issue by guhuawuli** [8go/matrix-commander#100]
First time use matrix-commander with docker command:
docker run --name matrix1 -v /Users/sm/desktop/:/data:z -it   matrixcommander/matrix-commander  --login "password" 

after answering all the questions that popped up

terminal tells me:
ERROR: matrix-commander: The program matrix-commander.py failed. Sorry.
ERROR: matrix-commander: can't start new thread
INFO: matrix-commander: 2 errors and 0 warnings occurred.

what's the problem? How to solve it?

**Comment by 8go** [comment]
I am not a docker expert, hence not a person to give docker advice. 

- Run it without docker to learn about `matrix-commander` in general. Verify your commands, etc.

- Run it in docker with `--debug` to see what is going on.

**Comment by hiiamboris** [comment]
Similar first run result here using `docker container run -a stdin -a stdout -a stderr matrixcommander/matrix-commander --login password --debug`:
```
2024-01-03 17:32:27,532:    DEBUG: matrix-commander: Debug is turned on. debug count=1
2024-01-03 17:32:27,535:    DEBUG: matrix-commander: Separator is set to "    " of length 4. E.g. Col1    Col2.
2024-01-03 17:32:27,536:    DEBUG: matrix-commander: Encryption is always enabled. It cannot be turned off. Use --tail to disable it for specific use cases.
2024-01-03 17:32:27,536:    DEBUG: matrix-commander: Option --sync is set to full.
2024-01-03 17:32:27,537:    DEBUG: matrix-commander: All arguments are valid. All checks passed.
2024-01-03 17:32:27,537:    DEBUG: matrix-commander: Create directory /root/.run for PID file.
2024-01-03 17:32:27,538:    DEBUG: matrix-commander: Trying to create a PID file to store process id 1.
2024-01-03 17:32:27,538:    DEBUG: matrix-commander: Successfully created PID file "/root/.run/matrix-commander.a20c1f4a-2b8c-469a-8941-3a5b0e673f88.pid" to store process id 1.
2024-01-03 17:32:27,538:    DEBUG: matrix-commander: Python version is "3.11.5 (main, Aug 28 2023, 00:00:00) [GCC 12.3.1 20230508 (Red Hat 12.3.1-1)]"
2024-01-03 17:32:27,539:    DEBUG: matrix-commander: Stdin pipe is assigned to "none".
2024-01-03 17:32:27,539:    DEBUG: matrix-commander: SSL will be used. Default SSL certificate validation will be done for this connection.
2024-01-03 17:32:27,540:    DEBUG: matrix-commander: Credentials file was specified with full path. So we suggest that one. file: /data/credentials.json
2024-01-03 17:32:27,540:    DEBUG: matrix-commander: Store directory "/data/store" was specified by user, it is a directory with a path, but the directory does not exist.
2024-01-03 17:32:27,540:    DEBUG: matrix-commander: Store directory was not found anywhere. Hence, we will suggest "/data/store" (local directory) as store directory.
2024-01-03 17:32:27,541:    DEBUG: matrix-commander: --login has chosen password method for authentication
2024-01-03 17:32:27,542:    ERROR: matrix-commander: E248: The program matrix-commander.py failed. Sorry.
2024-01-03 17:32:27,543:    DEBUG: matrix-commander: Cleanup: cleaning up.
2024-01-03 17:32:27,554:    ERROR: matrix-commander: EOF when reading a line
Here is the traceback.
Traceback (most recent call last):
  File "/app/matrix_commander/matrix_commander.py", line 9600, in main
    main_inner(argv)
  File "/app/matrix_commander/matrix_commander.py", line 9549, in main_inner
    asyncio.run(async_main())  # do everything in the event loop
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/matrix_commander/matrix_commander.py", line 6621, in async_main
    await action_login()  # explicit login
    ^^^^^^^^^^^^^^^^^^^^
  File "/app/matrix_commander/matrix_commander.py", line 6284, in action_login
    homeserver = input(f"Enter URL of your homeserver: [{homeserver}] ")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line

2024-01-03 17:32:27,555:     INFO: matrix-commander: 2 errors and 0 warnings occurred.
```
