### ISSUE TITLE
Question: installation on macOS x86_64 (vs macOS ARM like M1)

### ISSUE THREAD

**Issue by johannes87** [8go/matrix-commander#103]
OS: macOS 12.6.1

```
$ python3 --version
Python 3.10.8
$ pip3 --version
pip 22.3 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
```

I get the error `ModuleNotFoundError: No module named 'setuptools_scm'` when installing matrix-commander with pip.

Full output of `pip3 install matrix-commander`:
```
Collecting matrix-commander
  Using cached matrix_commander-3.5.19-py3-none-any.whl (134 kB)
Collecting asyncio
  Using cached asyncio-3.4.3-py3-none-any.whl (101 kB)
Collecting matrix-nio[e2e]>=0.14.1
  Downloading matrix_nio-0.20.0-py3-none-any.whl (173 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.7/173.7 kB 2.6 MB/s eta 0:00:00
Collecting aiohttp
  Using cached aiohttp-3.8.3-cp310-cp310-macosx_10_9_x86_64.whl (358 kB)
Collecting aiofiles>=0.6.0
  Using cached aiofiles-22.1.0-py3-none-any.whl (14 kB)
Collecting python-magic
  Downloading python_magic-0.4.27-py2.py3-none-any.whl (13 kB)
Collecting datetime
  Downloading DateTime-4.7-py2.py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.2/52.2 kB 3.6 MB/s eta 0:00:00
Collecting pyxdg
  Using cached pyxdg-0.28-py2.py3-none-any.whl (49 kB)
Collecting notify2
  Using cached notify2-0.3.1-py2.py3-none-any.whl (8.0 kB)
Collecting Pillow
  Downloading Pillow-9.3.0-cp310-cp310-macosx_10_10_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 24.2 MB/s eta 0:00:00
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting markdown
  Downloading Markdown-3.4.1-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.3/93.3 kB 5.4 MB/s eta 0:00:00
Collecting dbus-python
  Using cached dbus-python-1.3.2.tar.gz (605 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Collecting meson-python>=0.8.1
        Using cached meson_python-0.10.0-py3-none-any.whl (18 kB)
      Collecting meson>=0.60.0
        Using cached meson-0.63.3-py3-none-any.whl (926 kB)
      Collecting ninja
        Using cached ninja-1.10.2.4-py2.py3-none-macosx_10_9_universal2.macosx_10_9_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (231 kB)
      Collecting patchelf
        Using cached patchelf-0.16.1.0.tar.gz (157 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error

        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [17 lines of output]
            Error in sitecustomize; set PYTHONVERBOSE for traceback:
            AssertionError:
            Traceback (most recent call last):
              File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
                main()
              File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
                return hook(config_settings)
              File "/usr/local/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
                return self._get_build_requires(config_settings, requirements=['wheel'])
              File "/usr/local/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
                self.run_setup()
              File "/usr/local/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
                exec(code, locals())
              File "<string>", line 8, in <module>
            ModuleNotFoundError: No module named 'setuptools_scm'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by eli-schwartz** [comment]
This error occurs when trying to build `pip install patchelf` as a build time dependency of `pip install dbus-python`.

matrix-commander depends on notify2, which in turn depends on dbus-python (and mysteriously, matrix-commander includes that indirect dependency as an additional direct dependency :shrug:). So you need to somehow acquire dbus-python.

**Comment by 8go** [comment]
@eli-schwartz thank you for chiming in. That is helpful.

You are suggesting to remove `dbus-python` from `matrix-commander`s dependency list. 
Ok, I can do that. 

Would that fix the issue @johannes87 is having? Wouldn't it anyhow try to build `dbus-python` ? 
Would that be different on Mac than on Linux?

Any thoughts are welcome.

**Comment by 8go** [comment]
@johannes87 

Things to try: 
```
sudo apt install libdbus-1-dev libolm-dev # or the equivalent in MacOS
```

Please advise what the equivalent is so it can be placed into the documentation. 

```
pip3 install --user --upgrade dbus-python
pip3 install --user --upgrade notify2
```

Same here, if this is different on MacOS, let me know.

Please let me know what you did or will do to make it work so that it can be included in the doc for Mac users.

**Comment by 8go** [comment]
@johannes87 

The Mac documentation currently says:

See: https://pypi.org/project/matrix-commander/


```
or macOS Monterey 12.4 (21F79) (Apple M1 Pro) and similar please follow the these steps:

    Install libolm, dbus and libmagic using Homebrew
    Install matrix-commander using this command:
        pip3 install --global-option=build_ext --global-option="-I/opt/homebrew/include/" --global-option="-L/opt/homebrew/lib/" matrix-commander
    For more details see Issue #79. Thanks to @KizzyCode for the contribution.
```

So, installing `dbus` with `homebrew` might be the solution.

**Comment by 8go** [comment]
See commit [ea749a1](https://github.com/8go/matrix-commander/commit/ea749a17bbe678a2c50ca8dafbb0cdbacef477ad)

`dbus-python` has been removed from the requirements/dependencies.

Check out new version 3.5.24 on https://pypi.org/project/matrix-commander/3.5.24/

Same source code, but packaging has no `dbus-python` requirement, but to my understanding notify2 will require it anyway. Please comment.

**Comment by johannes87** [comment]
I tried 3.5.24, it stops with another error now. Here's the full log of `pip3 install matrix-commander`:

```
Collecting matrix-commander
  Using cached matrix_commander-3.5.24-py3-none-any.whl (134 kB)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: markdown in /usr/local/lib/python3.10/site-packages (from matrix-commander) (3.4.1)
Requirement already satisfied: notify2 in /usr/local/lib/python3.10/site-packages (from matrix-commander) (0.3.1)
Collecting matrix-nio[e2e]>=0.14.1
  Using cached matrix_nio-0.20.0-py3-none-any.whl (173 kB)
Requirement already satisfied: python-magic in /usr/local/lib/python3.10/site-packages (from matrix-commander) (0.4.27)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/site-packages (from matrix-commander) (9.3.0)
Requirement already satisfied: pyxdg in /usr/local/lib/python3.10/site-packages (from matrix-commander) (0.28)
Requirement already satisfied: datetime in /usr/local/lib/python3.10/site-packages (from matrix-commander) (4.7)
Collecting aiohttp
  Using cached aiohttp-3.8.3-cp310-cp310-macosx_10_9_x86_64.whl (358 kB)
Requirement already satisfied: uuid in /usr/local/lib/python3.10/site-packages (from matrix-commander) (1.30)
Requirement already satisfied: aiofiles>=0.6.0 in /usr/local/lib/python3.10/site-packages (from matrix-commander) (0.6.0)
Requirement already satisfied: asyncio in /usr/local/lib/python3.10/site-packages (from matrix-commander) (3.4.3)
Requirement already satisfied: pycryptodome<4.0.0,>=3.10.1 in /usr/local/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (3.15.0)
Requirement already satisfied: unpaddedbase64<3.0.0,>=2.1.0 in /usr/local/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (2.1.0)
Requirement already satisfied: h2<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (4.1.0)
Collecting aiohttp-socks<0.8.0,>=0.7.0
  Using cached aiohttp_socks-0.7.1-py3-none-any.whl (9.3 kB)
Requirement already satisfied: logbook<2.0.0,>=1.5.3 in /usr/local/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (1.5.3)
Requirement already satisfied: jsonschema<5.0.0,>=4.4.0 in /usr/local/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (4.17.0)
Requirement already satisfied: future<0.19.0,>=0.18.2 in /usr/local/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (0.18.2)
Requirement already satisfied: h11<0.13.0,>=0.12.0 in /usr/local/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (0.12.0)
Requirement already satisfied: cachetools<5.0.0,>=4.2.1 in /usr/local/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (4.2.4)
Requirement already satisfied: peewee<4.0.0,>=3.14.4 in /usr/local/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (3.15.3)
Collecting python-olm<4.0.0,>=3.1.3
  Using cached python-olm-3.1.3.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: atomicwrites<2.0.0,>=1.4.0 in /usr/local/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (1.4.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/site-packages (from aiohttp->matrix-commander) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/site-packages (from aiohttp->matrix-commander) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/site-packages (from aiohttp->matrix-commander) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/site-packages (from aiohttp->matrix-commander) (22.1.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.10/site-packages (from aiohttp->matrix-commander) (2.1.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/site-packages (from aiohttp->matrix-commander) (6.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/site-packages (from aiohttp->matrix-commander) (1.2.0)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.10/site-packages (from datetime->matrix-commander) (5.5.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/site-packages (from datetime->matrix-commander) (2022.6)
Requirement already satisfied: python-socks[asyncio]<3.0.0,>=2.0.0 in /usr/local/lib/python3.10/site-packages (from aiohttp-socks<0.8.0,>=0.7.0->matrix-nio[e2e]>=0.14.1->matrix-commander) (2.0.3)
Requirement already satisfied: hyperframe<7,>=6.0 in /usr/local/lib/python3.10/site-packages (from h2<5.0.0,>=4.0.0->matrix-nio[e2e]>=0.14.1->matrix-commander) (6.0.1)
Requirement already satisfied: hpack<5,>=4.0 in /usr/local/lib/python3.10/site-packages (from h2<5.0.0,>=4.0.0->matrix-nio[e2e]>=0.14.1->matrix-commander) (4.0.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.10/site-packages (from jsonschema<5.0.0,>=4.4.0->matrix-nio[e2e]>=0.14.1->matrix-commander) (0.19.2)
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.10/site-packages (from python-olm<4.0.0,>=3.1.3->matrix-nio[e2e]>=0.14.1->matrix-commander) (1.15.1)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.10/site-packages (from yarl<2.0,>=1.0->aiohttp->matrix-commander) (3.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (from zope.interface->datetime->matrix-commander) (65.4.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/site-packages (from cffi>=1.0.0->python-olm<4.0.0,>=3.1.3->matrix-nio[e2e]>=0.14.1->matrix-commander) (2.21)
Building wheels for collected packages: python-olm
  Building wheel for python-olm (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      make: *** No rule to make target `../include/olm/olm.h', needed by `include/olm/olm.h'.  Stop.
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-x86_64-cpython-310
      creating build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/sas.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/_finalize.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/utility.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/session.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/__init__.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/__version__.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/group_session.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/pk.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/_compat.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/account.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      running build_ext
      generating cffi module 'build/temp.macosx-12-x86_64-cpython-310/_libolm.c'
      creating build/temp.macosx-12-x86_64-cpython-310
      building '_libolm' extension
      creating build/temp.macosx-12-x86_64-cpython-310/build
      creating build/temp.macosx-12-x86_64-cpython-310/build/temp.macosx-12-x86_64-cpython-310
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c build/temp.macosx-12-x86_64-cpython-310/_libolm.c -o build/temp.macosx-12-x86_64-cpython-310/build/temp.macosx-12-x86_64-cpython-310/_libolm.o -I../include
      build/temp.macosx-12-x86_64-cpython-310/_libolm.c:570:18: fatal error: 'olm/olm.h' file not found
              #include <olm/olm.h>
                       ^~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-olm
  Running setup.py clean for python-olm
Failed to build python-olm
Installing collected packages: argparse, python-olm, aiohttp, aiohttp-socks, matrix-nio, matrix-commander
  Running setup.py install for python-olm ... error
  error: subprocess-exited-with-error

  × Running setup.py install for python-olm did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      make: *** No rule to make target `../include/olm/olm.h', needed by `include/olm/olm.h'.  Stop.
      running install
      /usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-x86_64-cpython-310
      creating build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/sas.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/_finalize.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/utility.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/session.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/__init__.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/__version__.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/group_session.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/pk.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/_compat.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      copying olm/account.py -> build/lib.macosx-12-x86_64-cpython-310/olm
      running build_ext
      generating cffi module 'build/temp.macosx-12-x86_64-cpython-310/_libolm.c'
      creating build/temp.macosx-12-x86_64-cpython-310
      building '_libolm' extension
      creating build/temp.macosx-12-x86_64-cpython-310/build
      creating build/temp.macosx-12-x86_64-cpython-310/build/temp.macosx-12-x86_64-cpython-310
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c build/temp.macosx-12-x86_64-cpython-310/_libolm.c -o build/temp.macosx-12-x86_64-cpython-310/build/temp.macosx-12-x86_64-cpython-310/_libolm.o -I../include
      build/temp.macosx-12-x86_64-cpython-310/_libolm.c:570:18: fatal error: 'olm/olm.h' file not found
              #include <olm/olm.h>
                       ^~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-olm

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

Here's the full log of `pip3 install --global-option=build_ext --global-option="-I/opt/homebrew/include/" --global-option="-L/opt/homebrew/lib/" matrix-commander`. I installed libolm, dbus and libmagic with homebrew before::

```
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option / --install-option. Consider using --config-settings for more flexibility.
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Collecting matrix-commander
  Using cached matrix-commander-3.5.24.tar.gz (188 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp
  Using cached aiohttp-3.8.3.tar.gz (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting argparse
  Using cached argparse-1.4.0.tar.gz (70 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-magic in /usr/local/lib/python3.10/site-packages (from matrix-commander) (0.4.27)
Requirement already satisfied: notify2 in /usr/local/lib/python3.10/site-packages (from matrix-commander) (0.3.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/site-packages (from matrix-commander) (9.3.0)
Requirement already satisfied: asyncio in /usr/local/lib/python3.10/site-packages (from matrix-commander) (3.4.3)
Requirement already satisfied: aiofiles>=0.6.0 in /usr/local/lib/python3.10/site-packages (from matrix-commander) (0.6.0)
Requirement already satisfied: pyxdg in /usr/local/lib/python3.10/site-packages (from matrix-commander) (0.28)
Requirement already satisfied: datetime in /usr/local/lib/python3.10/site-packages (from matrix-commander) (4.7)
Requirement already satisfied: markdown in /usr/local/lib/python3.10/site-packages (from matrix-commander) (3.4.1)
Requirement already satisfied: uuid in /usr/local/lib/python3.10/site-packages (from matrix-commander) (1.30)
Collecting matrix-nio[e2e]>=0.14.1
  Using cached matrix-nio-0.20.0.tar.gz (147 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 400, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 577, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 685, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 173, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 319, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry'
``` 

I'm using the x86_64 version of macOS.

**Comment by 8go** [comment]
I am stating just the obvious: on first run it says "olm.h missing". On the second run it says "poetry" missing. 

Searching hard disk for olm.h. This hints at that the Development package of libolm is missing. The dev package has the .h files. So, check if there is a dev package for olm for your hardware platform.

Installing poetry?

**Comment by johannes87** [comment]
It's working now, thanks. What I needed to do in the end:

- `brew install libolm`
- `pip3 install poetry`
- `pip3 install --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-L/usr/local/lib/" matrix-commander`

I needed /usr/local instead of /opt/homebrew, the path is different. I guess the path is different because I'm using x86_64 macOS, not arm.

Question: why is poetry not automatically installed as a dependency?

**Comment by 8go** [comment]
Question: why is poetry not automatically installed as a dependency?

Because this is a MacOS specific thing.

**Comment by 8go** [comment]
Could you write up your success installation story in about 5 lines? 

Something like `On platform X, OS verions Y, do these 4 steps for installation: ...`

and I will place it into the documentation to help other Mac users. :pray:

**Comment by eli-schwartz** [comment]
Poetry is not required, but poetry_core is a build dependency for `matrix-nio`, and of course matrix-commander depends on that. It really should be getting installed by pip, though -- that is pip's job.

**Comment by johannes87** [comment]
On macOS x86_64, do these steps for installation:
- `brew install libolm dbus libmagic`
- `pip3 install poetry`
- `pip3 install --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-L/usr/local/lib/" matrix-commander`

Not sure if dbus and libmagic are needed.
