### ISSUE TITLE
Bug: Creating a room without an alias fails

### ISSUE THREAD

**Issue by edwinsage** [8go/matrix-commander#104]
The documentation says you can pass an empty string to `--room-create`, but it fails when doing so.

    ERROR: matrix-commander: Room creation failed. Sorry.
    DEBUG: matrix-commander: Here is the traceback.
    Traceback (most recent call last):
      File "/home/moist/.local/lib/python3.9/site-packages/matrix_commander/matrix_commander.py", line 3536, in action_room_create
        full_alias = short_room_alias_to_room_alias(alias, credentials)
      File "/home/moist/.local/lib/python3.9/site-packages/matrix_commander/matrix_commander.py", line 3297, in short_room_alias_to_room_alias
        raise MatrixCommanderError(err) from None
    matrix_commander.matrix_commander.MatrixCommanderError: Invalid room alias. Alias is none or empty.

Apparently it is indeed creating a room, but it fails when parsing the response and incorrectly reports that room creation failed.

**Comment by 8go** [comment]
Thank you :clap: :clap: :clap: @edwinsage for finding the bug. 
Fixed.
