### ISSUE TITLE
Bug: Running with `--joined-members` fails

### ISSUE THREAD

**Issue by edwinsage** [8go/matrix-commander#105]
Trying to run with `--joined-members` fails, possibly due to avatar_url being None for some members?  I'm not entirely certain.  Here's the traceback.

    ERROR: matrix-commander: Error during room, set, get actions. Continuing despite error. Exception: can only concatenate str (not "NoneType") to str
    DEBUG: matrix-commander: Here is the traceback.
    Traceback (most recent call last):
      File "/home/moist/.local/lib/python3.9/site-packages/matrix_commander/matrix_commander.py", line 6864, in action_roomsetget
        await action_joined_members(gs.client, gs.credentials)
      File "/home/moist/.local/lib/python3.9/site-packages/matrix_commander/matrix_commander.py", line 5703, in action_joined_members
        SEP
    TypeError: can only concatenate str (not "NoneType") to str

**Comment by 8go** [comment]
Thank you :clap: :clap: :clap: @edwinsage for finding the bug. 
Fixed.
