### ISSUE TITLE
Dependency on async_timeout

### ISSUE THREAD

**Issue by Marcool04** [8go/matrix-commander#161]
Hi there.

I have been maintaining a [PKGBUILD](https://aur.archlinux.org/packages/matrix-commander) for matrix-commander in the Arch Linux User Repository for a little while, and today somebody pointed out that this package should depend on the Arch Linux package [python-async-timeout](https://archlinux.org/packages/extra/any/python-async-timeout/), which is [async_timeout](https://pypi.org/project/async-timeout/) on Pypi.

I had not noticed this, which led me to investigate. I realised that, until a few versions ago, [aiohttp](https://pypi.org/project/aiohttp/) - which matrix-commander depends on - itself depended on `async_timeout`, but that it now no longer does: https://github.com/aio-libs/aiohttp/releases/tag/v3.9.0. However, matrix-commander does actually use `async_timeout` directly, since when I uninstall it and try and run matrix-commander I get:

```
Traceback (most recent call last):
File "/usr/bin/matrix-commander", line 5, in <module>
from matrix_commander import main
File "/usr/lib/python3.11/site-packages/matrix_commander/__init__.py", line 1, in <module>
from .matrix_commander import main
File "/usr/lib/python3.11/site-packages/matrix_commander/matrix_commander.py", line 51, in <module>
from nio import (AsyncClient, AsyncClientConfig, ContentRepositoryConfigError,
File "/usr/lib/python3.11/site-packages/nio/__init__.py", line 9, in <module>
from .client import *
File "/usr/lib/python3.11/site-packages/nio/client/__init__.py", line 7, in <module>
from .async_client import AsyncClient, AsyncClientConfig, DataProvider
File "/usr/lib/python3.11/site-packages/nio/client/async_client.py", line 57, in <module>
from aiohttp_socks import ProxyConnector
File "/usr/lib/python3.11/site-packages/aiohttp_socks/__init__.py", line 11, in <module>
from .connector import (
File "/usr/lib/python3.11/site-packages/aiohttp_socks/connector.py", line 10, in <module>
from python_socks.async_.asyncio.v2 import Proxy
File "/usr/lib/python3.11/site-packages/python_socks/async_/asyncio/__init__.py", line 1, in <module>
from ._proxy import AsyncioProxy as Proxy
File "/usr/lib/python3.11/site-packages/python_socks/async_/asyncio/_proxy.py", line 5, in <module>
import async_timeout
No module named 'async_timeout'
```

So I guess the solution is just that matrix-commander should depend, itself, on `async_timeout` in its requirements.txt, maybe?

Thanks for the useful tool.
Best regards,
Mark.

**Comment by 8go** [comment]
Fixed in release 7.6.2

Thank you @Marcool04 for bringing this to my attention :heart: 

If there is still an issue on Arch then please re-open issue, Thnanks.
