### ISSUE TITLE
AttributeError: module 'olm' has no attribute 'Sas'

### ISSUE THREAD

**Issue by takiainen** [8go/matrix-commander#37]
Been trying to make this work on Raspberry Pi 3 for several hours. 

Currently running 
python matrix-commander.py

results in this:
Traceback (most recent call last):
  File "/home/pi/matrix-commander/matrix-commander.py", line 690, in <module>
    from nio import (
  File "/home/pi/.local/lib/python3.9/site-packages/nio/__init__.py", line 2, in <module>
    from .client import *
  File "/home/pi/.local/lib/python3.9/site-packages/nio/client/__init__.py", line 3, in <module>
    from .base_client import Client, ClientConfig
  File "/home/pi/.local/lib/python3.9/site-packages/nio/client/base_client.py", line 35, in <module>
    from ..crypto import ENCRYPTION_ENABLED
  File "/home/pi/.local/lib/python3.9/site-packages/nio/crypto/__init__.py", line 41, in <module>
    from .olm_machine import Olm
  File "/home/pi/.local/lib/python3.9/site-packages/nio/crypto/olm_machine.py", line 54, in <module>
    from .sas import Sas
  File "/home/pi/.local/lib/python3.9/site-packages/nio/crypto/sas.py", line 49, in <module>
    class Sas(olm.Sas):
AttributeError: module 'olm' has no attribute 'Sas'

What to do? 
------------------------------

EDIT: Got it working by deleting pip cache and reinstalling everything.

**Comment by 8go** [comment]
Thanks @takiainen for taking the time to report it. 

This looks like an olm version problem. Remember to always use Olm v3.
I am glad you could resolve it. 

Regarding olm installation there was already an issue raised in the past in a related project. If still interested have a look at Issue https://github.com/8go/matrix-eno-bot/issues/6
