### ISSUE TITLE
"matrix-commander: KeyError: 'invite'"

### ISSUE THREAD

**Issue by ManOrs88** [8go/matrix-commander#39]
Hello,

not sure if this goes here or should be reported to nio library as it's the one that seems to really be erroring out,
today i started getting "room is not existent" errors when trying to send a message from a cron script,
i however know for sure the room id is correct as other crons which do a plain curl call are correctly working,
now that i tried adding debug level i can not reproduce it anymore, which is weird by itself

tried the listening mode to exclude issues with the room and got the traceback below

matrix-commander lives in its own pyenv which just today got updated from 3.8.10 to 3.8.11,
i recreated the env, so likely all the dependencies have been updated too, full "pip freeze" is at the end,
matrix-commander is at commit 06b4738bc74ee86fb3ac88c04b8230abf82e7421

side issue: the message "The program matrix-commander.py failed. Sorry. Here is the traceback." should not be "INFO" level

```
$ python matrix-commander.py -dd -l once
2021-07-01 21:38:10,277:    DEBUG: matrix-commander: Debug is turned on. debug count=2
2021-07-01 21:38:10,277:    DEBUG: matrix-commander: Encryption is always enabled. It cannot be turned off.
2021-07-01 21:38:10,277:    DEBUG: matrix-commander: All arguments are valid. All checks passed.
2021-07-01 21:38:10,277:    DEBUG: matrix-commander: Trying to create a PID file to store process id ###.
2021-07-01 21:38:10,277:    DEBUG: matrix-commander: Successfully created PID file "/home/user/.run/matrix-commander.<uuid>.pid" to store process id ###.
2021-07-01 21:38:10,277:    DEBUG:          asyncio: Using selector: EpollSelector
2021-07-01 21:38:10,278:    DEBUG: matrix-commander: Credentials file existed. So this is the one we suggest to use. file: credentials.json
2021-07-01 21:38:10,278:    DEBUG: matrix-commander: Found an existing store in directory "store" (local or arguments). It will be used.
2021-07-01 21:38:10,278:    DEBUG: matrix-commander: Credentials file does exist.
2021-07-01 21:38:10,299:    DEBUG:           peewee: <cut>
2021-07-01 21:38:10,300:    DEBUG: matrix-commander: Logged in using stored credentials from credentials file "credentials.json".
2021-07-01 21:38:10,300:    DEBUG: matrix-commander: Logged_in() = True
2021-07-01 21:38:10,300:    DEBUG: matrix-commander: Listening type: once
2021-07-01 21:38:11,000:     INFO: matrix-commander: The program matrix-commander.py failed. Sorry. Here is the traceback.
2021-07-01 21:38:11,312:     INFO: matrix-commander: Traceback (most recent call last):
  File "matrix-commander.py", line 2901, in listen_all
    resp_s = await client.sync(timeout=10000, full_state=True)
  File "/home/user/.pyenv/versions/matrix-commander/lib/python3.8/site-packages/nio/client/async_client.py", line 1028, in sync
    response = await self._send(
  File "/home/user/.pyenv/versions/matrix-commander/lib/python3.8/site-packages/nio/client/async_client.py", line 743, in _send
    resp = await self.create_matrix_response(
  File "/home/user/.pyenv/versions/matrix-commander/lib/python3.8/site-packages/nio/client/async_client.py", line 520, in create_matrix_response
    resp = response_class.from_dict(parsed_dict, *data)
  File "/home/user/.pyenv/versions/matrix-commander/lib/python3.8/site-packages/nio/responses.py", line 178, in wrapper
    return f(cls, parsed_dict, *args, **kwargs)
  File "/home/user/.pyenv/versions/matrix-commander/lib/python3.8/site-packages/nio/responses.py", line 1761, in from_dict
    rooms = SyncResponse._get_room_info(parsed_dict["rooms"])
  File "/home/user/.pyenv/versions/matrix-commander/lib/python3.8/site-packages/nio/responses.py", line 1697, in _get_room_info
    for room_id, room_dict in parsed_dict["invite"].items():
KeyError: 'invite'

2021-07-01 21:38:11,312:    DEBUG: matrix-commander: The program matrix-commander.py terminated successfully.
2021-07-01 21:38:11,312:    DEBUG: matrix-commander: Cleanup: cleaning up.
```

```
aiofiles==0.4.0
aiohttp==3.7.4.post0
aiohttp-socks==0.5.5
async-timeout==3.0.1
asyncio==3.4.3
atomicwrites==1.4.0
attrs==21.2.0
cachetools==4.2.2
cffi==1.14.5
chardet==4.0.0
DateTime==4.3
future==0.18.2
h11==0.9.0
h2==3.2.0
hpack==3.0.0
hyperframe==5.2.0
idna==3.2
jsonschema==3.2.0
Logbook==1.5.3
Markdown==3.3.4
matrix-nio==0.17.0
multidict==5.1.0
peewee==3.14.4
Pillow==8.3.0
pycparser==2.20
pycryptodome==3.10.1
pyrsistent==0.18.0
python-magic==0.4.24
python-olm==3.1.3
python-socks==1.2.4
pytz==2021.1
six==1.16.0
typing-extensions==3.10.0.0
unpaddedbase64==1.1.0
uuid==1.30
yarl==1.6.3
zope.interface==5.4.0
```

**Comment by ManOrs88** [comment]
in an even weirder turn it now works correctly, maybe if was something server side...

**Comment by 8go** [comment]
Sorry @ManOrs88 . Not sure what was happening. 

But I used your comments to change the debug level from INFO to ERROR and fixed another misleading debug string. 
So, your observations did make the program a tiny tiny bit better.
