### ISSUE TITLE
error

### ISSUE THREAD

**Issue by takiainen** [8go/matrix-commander#40]
Currently running matrix-commander on raspberry pi 4. Using Python-3.9.5. 
It used to work, but then it just stopped working. Here's what happens if I manually start it.

~/matrix-commander $ python matrix-commander.py --version

  _|      _|      _|_|_|    _|       matrix-commander
  _|_|  _|_|    _|            _|     a Matrix CLI client
  _|  _|  _|    _|              _|   
  _|      _|    _|            _|     version 2021-May-25
  _|      _|      _|_|_|    _|       enjoy and submit PRs

2021-07-02 21:53:47,759:     INFO: matrix-commander: The program matrix-commander.py failed. Sorry. Here is the traceback.
2021-07-02 21:53:47,772:     INFO: matrix-commander: Traceback (most recent call last):
  File "/home/pi/matrix-commander/matrix-commander.py", line 3137, in main_send
    client, credentials = login_using_credentials_file(
  File "/home/pi/matrix-commander/matrix-commander.py", line 2561, in login_using_credentials_file
    client.restore_login(
  File "/home/pi/.local/lib/python3.9/site-packages/nio/client/base_client.py", line 407, in restore_login
    self.load_store()
  File "/home/pi/.local/lib/python3.9/site-packages/nio/client/base_client.py", line 383, in load_store
    self.olm = Olm(self.user_id, self.device_id, self.store)
  File "/home/pi/.local/lib/python3.9/site-packages/nio/crypto/olm_machine.py", line 213, in __init__
    account = self.store.load_account()  # type: ignore
  File "/home/pi/.local/lib/python3.9/site-packages/nio/store/database.py", line 166, in load_account
    return OlmAccount.from_pickle(
  File "/home/pi/.local/lib/python3.9/site-packages/nio/crypto/sessions.py", line 45, in from_pickle
    account = super().from_pickle(pickle, passphrase)
  File "/home/pi/.local/lib/python3.9/site-packages/olm/account.py", line 166, in from_pickle
    obj._check_error(ret)
  File "/home/pi/.local/lib/python3.9/site-packages/olm/account.py", line 99, in _check_error
    raise OlmAccountError(last_error)
olm.account.OlmAccountError: UNKNOWN_PICKLE_VERSION

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/matrix-commander/matrix-commander.py", line 4041, in <module>
    asyncio.get_event_loop().run_until_complete(main_send())
  File "/usr/local/opt/python-3.9.5/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/matrix-commander/matrix-commander.py", line 3155, in main_send
    if client:
UnboundLocalError: local variable 'client' referenced before assignment

---------------------

EDIT:
I deleted credentials.json and STORE directory and started all over. However, when I'm trying to verify via terminal, I finally get this error:

python matrix-commander.py --verify
This program is ready and waiting for the other party to initiate an emoji verification with us by selecting "Verify by Emoji"in their Matrix client.
2021-07-02 23:47:37,897:     INFO: matrix-commander: The program matrix-commander.py failed. Sorry. Here is the traceback.
2021-07-02 23:47:37,907:     INFO: matrix-commander: Traceback (most recent call last):
  File "/home/pi/matrix-commander/matrix-commander.py", line 4019, in <module>
    asyncio.get_event_loop().run_until_complete(main_verify())
  File "/usr/local/opt/python-3.9.5/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/matrix-commander/matrix-commander.py", line 3122, in main_verify
    await client.sync_forever(timeout=30000, full_state=True)
  File "/home/pi/.local/lib/python3.9/site-packages/nio/client/async_client.py", line 1155, in sync_forever
    sync_response = await self.sync(use_timeout, use_filter, since, full_state, presence)
  File "/home/pi/.local/lib/python3.9/site-packages/nio/client/async_client.py", line 1028, in sync
    response = await self._send(
  File "/home/pi/.local/lib/python3.9/site-packages/nio/client/async_client.py", line 743, in _send
    resp = await self.create_matrix_response(
  File "/home/pi/.local/lib/python3.9/site-packages/nio/client/async_client.py", line 520, in create_matrix_response
    resp = response_class.from_dict(parsed_dict, *data)
  File "/home/pi/.local/lib/python3.9/site-packages/nio/responses.py", line 178, in wrapper
    return f(cls, parsed_dict, *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/nio/responses.py", line 1761, in from_dict
    rooms = SyncResponse._get_room_info(parsed_dict["rooms"])
  File "/home/pi/.local/lib/python3.9/site-packages/nio/responses.py", line 1697, in _get_room_info
    for room_id, room_dict in parsed_dict["invite"].items():
KeyError: 'invite'

cannot get past this. 
It doesn't help if I log in with my username via browser and complete verifications etc, matrix-commander shows the same above message. I cannot send a single message.

**Comment by Jochem22** [comment]
try updating matrix-nio

**Comment by 8go** [comment]
Any update on this issue @takiainen ? 

Thanks @Jochem22 for the suggestion. 

@takiainen Did you try updating all dependencies, from matrix-nio, olm, etc.? As well as updating all pip packages you might have in your environment?

**Comment by takiainen** [comment]
Thanks for your help, updating matrix-nio did the trick. Everything working smoothly now!

**Comment by 8go** [comment]
@takiainen  I am glad to hear that :+1: 

thanks @Jochem22
