### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by dm-msk** [8go/matrix-commander#44]
2021-07-23 14:42:16,219:     INFO: matrix-commander: Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'matrix.example.com'. (_ssl.c:1108)

How to skip this check?

**Comment by dm-msk** [comment]
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host matrix.aresbank.ru:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'matrix.example.com'. (_ssl.c:1108)")]

**Comment by 8go** [comment]
Do you have an SSL certificate?
Is your Matrix server accessible through other clients, like Element?
Where is 'matrix.example.com' seen in the error coming from?

**Comment by dm-msk** [comment]
> Do you have an SSL certificate?
> Is your Matrix server accessible through other clients, like Element?
> Where is 'matrix.example.com' seen in the error coming from?

Hello. We have valid Globalsign certificate. There are many Element clients work fine with this server. 
When I try to perform first run of matrix-commander I got this error after password confirmation. If I open the browser and perform matrix.example.com the certificate chain is valid.

**Comment by 8go** [comment]
I still don't understand. What has `matrix.example.com` have to do with all this? `matrix.example.com` is not your server. How is it possible that it shows up in the SSL error?

**Comment by dm-msk** [comment]
matrix.example.com I take as example chanched log output. We have another name of domain that I cannot announced on public resources by information security policy. My question was how to skip this check. For example in curl option -k. Also Python have same options for those functions. It will be perfect to have a flag in a script.

**Comment by 8go** [comment]
Your explanation now makes sense. 

I don't think I can solve your problem. I can only make 2 neutral comments. Maybe they can help you further.
a) You are the only one with this problem. This surprise me a bit. 
b) Could it have something to do with sub-domains? Certificate for `*.example.com` vs `matrix.example.com`?
c) That functionality (related to certificate check vs skipping check) is not in `matrix-commander`. At best it is in `matrix-nio`, but possibly even lower that that. 

Sorry.

**Comment by dm-msk** [comment]
Wildcard certificate for *.example.com

**Comment by 8go** [comment]
Hi @dm-msk 

There are no new feaures in `matrix-commander` including `--no-ssl` which will skip SSL certificate validation. This is what you asked for on Jul 24,2021. This should fix your problem.

Also, note that there is `--ssl-certificate` where you can specify your local SSL certificate file. 

Good luck!

**Comment by 8go** [comment]
Closing issue, reopen it if necessary.
