### ISSUE TITLE
Bug: SSO fails on a headless server

### ISSUE THREAD

**Issue by GitHubForSnap** [8go/matrix-commander#71]
Hi there,

When running matrix-commander for the 1st time on a headless server, the initialization fails if the server returns the login flow "m.login.sso".

On a system with no browser, matrix-commander should not try to use the login flow "m.login.sso".

Thank you

```
ubuntu@lavish-batfish:~/matrix-commander$ ./matrix-commander.py --debug
2022-05-19 22:38:44,022:    DEBUG: matrix-commander: Debug is turned on. debug count=1
2022-05-19 22:38:44,023:    DEBUG: matrix-commander: Encryption is always enabled. It cannot be turned off.
2022-05-19 22:38:44,023:    DEBUG: matrix-commander: All arguments are valid. All checks passed.
2022-05-19 22:38:44,024:    DEBUG: matrix-commander: Trying to create a PID file to store process id 34583.
2022-05-19 22:38:44,024:    DEBUG: matrix-commander: Successfully created PID file "/home/ubuntu/.run/matrix-commander.d597c882-960f-4cf0-b0bb-5550717ed258.pid" to store process id 34583.
2022-05-19 22:38:44,024:    DEBUG: matrix-commander: Stdin pipe is assigned to "none".
2022-05-19 22:38:44,025:    DEBUG: matrix-commander: Credentials file does not exist locally. File name has no path.
2022-05-19 22:38:44,025:    DEBUG: matrix-commander: Trying path "/home/ubuntu/.config/matrix-commander/credentials.json" as last resort. Suggesting to look for it there.
2022-05-19 22:38:44,025:    DEBUG: matrix-commander: File does not exists either in the last resort directory or the local directory. File not found anywhere. One will have to be created. So we suggest the local directory.
2022-05-19 22:38:44,025:    DEBUG: matrix-commander: Could not find an existing store directory anywhere. 
There are 2 possibilities:
1) This is the first time you use matrix-commander or you want to create a new store. In this first case just continue, and a new store will be created. It will need to be verified. The store directory will be created in the directory "store". Optionally, consider moving he persistant storage directory files inside "store" into the directory "/home/ubuntu/.local/share/matrix-commander/store" for a more consistent experience.
2) You specified the store location incorrectly or you started matrix-commander from the wrong directory. In this second case abort, change you directory if needed or set the store option correctly. Then start matrix-commander again.
Could not find an existing store directory anywhere.
There are 2 possibilities:
1) This is the first time you use matrix-commander or you want to create a new
   store. In this first case just continue, and a new store will be created. It
   will need to be verified. The store directory will be created in the
   directory "store". Optionally, consider moving he persistant storage
   directory files inside "store" into the directory
   "/home/ubuntu/.local/share/matrix-commander/store" for a more consistent
   experience.
2) You specified the store location incorrectly or you started matrix-commander
   from the wrong directory. In this second case abort, change you directory if
   needed or set the store option correctly. Then start matrix-commander again.
2022-05-19 22:38:44,026:    DEBUG: matrix-commander: Credentials file does not exist.
Credentials file "credentials.json" was not found. There are 2 possibilities
   for this.
1) This is your first time use? Setting up new credentials? Then welcome to
   matrix-commander. Continue, and in the next step you will be asked for
   homeserver, user, password and room id to create a credentials file.
2) You specified the credentials location incorrectly or you started matrix-
   commander from the wrong directory. Abort, change you directory if needed or
   set the credentials option correctly. Then start matrix-commander again.
Continue to create new credentials? (Yes or Ctrl-C to abort) Yes
Enter URL of your homeserver: [https://matrix.example.org] https://matrix.org
2022-05-19 22:39:23,658:     INFO: matrix-commander: SSL will be used. Default SSL certificate validation will be done for this connection.
2022-05-19 22:39:23,740:    DEBUG: matrix-commander: Supported login flows: {'m.login.password', 'm.login.application_service', 'm.login.sso', 'm.login.token'}
Choose a name for this device: [matrix-commander] 
Enter your room ID: [!SomeRoomIdString:example.org] !MyRoomID:matrix.org
Launching browser to complete SSO login.
2022-05-19 22:39:37,717:    ERROR: matrix-commander: The program matrix-commander.py failed. Sorry. Here is the traceback.
2022-05-19 22:39:37,722:    ERROR: matrix-commander: Traceback (most recent call last):
  File "./matrix-commander.py", line 4457, in <module>
    asyncio.run(main_send())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./matrix-commander.py", line 3476, in main_send
    await create_credentials_file(credentials_file, store_dir)
  File "./matrix-commander.py", line 2715, in create_credentials_file
    subprocess.check_output(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1585, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

2022-05-19 22:39:37,724:    DEBUG: matrix-commander: Cleanup: cleaning up.
```

**Comment by 8go** [comment]
It is trying to start a browser (for SSO), which will fail of course on a head-less server. 
Let me look into this.

**Comment by 8go** [comment]
Hi @GitHubForSnap 

Thank you :clap: for bringing this to my attention.

The latest commit [eda34a3](https://github.com/8go/matrix-commander/commit/eda34a38e7da6d4513448f16c2a76d46faecd821) should fix this. 

Can you please :pray: test the latest version to make sure it works for you now. 

Tell us if it worked! Cheers

**Comment by GitHubForSnap** [comment]
Hi @8go,

I used the new --no-sso flag on the first run.

```
matrix-commander --no-sso
```

It worked like a charm.

Thanks for the quick fix.
Cheers

**Comment by 8go** [comment]
Glad to hear that @GitHubForSnap ! :+1: 
Closing issue.
