### ISSUE TITLE
PIP-installation fails under macOS

### ISSUE THREAD

**Issue by KizzyCode** [8go/matrix-commander#79]
The PIP-installation-instructions fail under macOS (`macOS Monterey 12.4 (21F79), Apple M1 Pro`). The faulty packages seems to be `dbus-python` and `python-olm` (`libolm` has been installed via homebrew).

<details>

```
Collecting matrix-commander
  Using cached matrix_commander-2.34.0-py3-none-any.whl (101 kB)
Collecting matrix-nio[e2e]>=0.14.1
  Using cached matrix_nio-0.19.0-py3-none-any.whl (174 kB)
Collecting Pillow
  Using cached Pillow-9.1.1-cp39-cp39-macosx_11_0_arm64.whl (2.8 MB)
Collecting aiofiles>=0.6.0
  Using cached aiofiles-0.8.0-py3-none-any.whl (13 kB)
Collecting python-magic
  Using cached python_magic-0.4.27-py2.py3-none-any.whl (13 kB)
Collecting datetime
  Using cached DateTime-4.4-py2.py3-none-any.whl (51 kB)
Collecting dbus-python
  Using cached dbus-python-1.2.18.tar.gz (578 kB)
  Preparing metadata (setup.py) ... done
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting asyncio
  Using cached asyncio-3.4.3-py3-none-any.whl (101 kB)
Collecting markdown
  Using cached Markdown-3.3.7-py3-none-any.whl (97 kB)
Collecting aiohttp
  Using cached aiohttp-3.8.1-cp39-cp39-macosx_11_0_arm64.whl (552 kB)
Requirement already satisfied: notify2 in /opt/homebrew/lib/python3.9/site-packages (from matrix-commander) (0.3.1)
Requirement already satisfied: uuid in /opt/homebrew/lib/python3.9/site-packages (from matrix-commander) (1.30)
Collecting aiofiles>=0.6.0
  Using cached aiofiles-0.6.0-py3-none-any.whl (11 kB)
Collecting h2<5.0.0,>=4.0.0
  Using cached h2-4.1.0-py3-none-any.whl (57 kB)
Collecting jsonschema<4.0.0,>=3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Requirement already satisfied: logbook<2.0.0,>=1.5.3 in /opt/homebrew/lib/python3.9/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (1.5.3)
Collecting unpaddedbase64<3.0.0,>=2.1.0
  Using cached unpaddedbase64-2.1.0-py3-none-any.whl (6.1 kB)
Collecting h11<0.13.0,>=0.12.0
  Using cached h11-0.12.0-py3-none-any.whl (54 kB)
Collecting aiohttp-socks<0.8.0,>=0.7.0
  Using cached aiohttp_socks-0.7.1-py3-none-any.whl (9.3 kB)
Collecting future<0.19.0,>=0.18.2
  Using cached future-0.18.2-py3-none-any.whl
Collecting pycryptodome<4.0.0,>=3.10.1
  Using cached pycryptodome-3.14.1-cp35-abi3-macosx_12_0_arm64.whl
Collecting atomicwrites<2.0.0,>=1.4.0
  Using cached atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting python-olm<4.0.0,>=3.1.3
  Using cached python-olm-3.1.3.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Collecting cachetools<5.0.0,>=4.2.1
  Using cached cachetools-4.2.4-py3-none-any.whl (10 kB)
Requirement already satisfied: peewee<4.0.0,>=3.14.4 in /opt/homebrew/lib/python3.9/site-packages (from matrix-nio[e2e]>=0.14.1->matrix-commander) (3.14.10)
Collecting attrs>=17.3.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting charset-normalizer<3.0,>=2.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.0-cp39-cp39-macosx_11_0_arm64.whl (34 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.7.2-cp39-cp39-macosx_11_0_arm64.whl (118 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.2-cp39-cp39-macosx_11_0_arm64.whl (29 kB)
Collecting zope.interface
  Using cached zope.interface-5.4.0-cp39-cp39-macosx_12_0_arm64.whl
Requirement already satisfied: pytz in /opt/homebrew/lib/python3.9/site-packages (from datetime->matrix-commander) (2022.1)
Collecting importlib-metadata>=4.4
  Using cached importlib_metadata-4.11.4-py3-none-any.whl (18 kB)
Requirement already satisfied: python-socks[asyncio]<3.0.0,>=2.0.0 in /opt/homebrew/lib/python3.9/site-packages (from aiohttp-socks<0.8.0,>=0.7.0->matrix-nio[e2e]>=0.14.1->matrix-commander) (2.0.3)
Collecting hpack<5,>=4.0
  Using cached hpack-4.0.0-py3-none-any.whl (32 kB)
Collecting hyperframe<7,>=6.0
  Using cached hyperframe-6.0.1-py3-none-any.whl (12 kB)
Collecting zipp>=0.5
  Using cached zipp-3.8.0-py3-none-any.whl (5.4 kB)
Collecting six>=1.11.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyrsistent>=0.14.0
  Using cached pyrsistent-0.18.1-cp39-cp39-macosx_10_9_universal2.whl (81 kB)
Requirement already satisfied: setuptools in /opt/homebrew/lib/python3.9/site-packages (from jsonschema<4.0.0,>=3.2.0->matrix-nio[e2e]>=0.14.1->matrix-commander) (62.3.2)
Collecting cffi>=1.0.0
  Using cached cffi-1.15.0-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
Collecting idna>=2.0
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: dbus-python, python-olm
  Building wheel for dbus-python (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [160 lines of output]
      running bdist_wheel
      running build
      creating /private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/build
      creating /private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/build/temp.macosx-12-arm64-cpython-39
      checking whether make supports nested variables... yes
      checking whether to enable maintainer-specific portions of Makefiles... no
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to accept ISO C89... none needed
      checking whether gcc understands -c and -o together... yes
      checking how to run the C preprocessor... gcc -E
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking minix/config.h usability... no
      checking minix/config.h presence... no
      checking for minix/config.h... no
      checking whether it is safe to define __EXTENSIONS__... yes
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a thread-safe mkdir -p... /private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/build-aux/install-sh -c -d
      checking for gawk... no
      checking for mawk... no
      checking for nawk... no
      checking for awk... awk
      checking whether make sets $(MAKE)... yes
      checking whether make supports the include directive... yes (GNU style)
      checking whether UID '501' is supported by ustar format... yes
      checking whether GID '20' is supported by ustar format... yes
      checking how to create a ustar tar archive... gnutar
      checking dependency style of gcc... gcc3
      checking build system type... arm-apple-darwin21.5.0
      checking host system type... arm-apple-darwin21.5.0
      checking for native Windows host... no
      checking how to print strings... printf
      checking for a sed that does not truncate output... /usr/bin/sed
      checking for fgrep... /usr/bin/grep -F
      checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
      checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
      checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
      checking the name lister (/usr/bin/nm -B) interface... BSD nm
      checking whether ln -s works... yes
      checking the maximum length of command line arguments... 786432
      checking how to convert arm-apple-darwin21.5.0 file names to arm-apple-darwin21.5.0 format... func_convert_file_noop
      checking how to convert arm-apple-darwin21.5.0 file names to toolchain format... func_convert_file_noop
      checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
      checking for objdump... objdump
      checking how to recognize dependent libraries... pass_all
      checking for dlltool... no
      checking how to associate runtime and link libraries... printf %s\n
      checking for ar... ar
      checking for archiver @FILE support... no
      checking for strip... strip
      checking for ranlib... ranlib
      checking command to parse /usr/bin/nm -B output from gcc object... ok
      checking for sysroot... no
      checking for a working dd... /bin/dd
      checking how to truncate binary pipes... /bin/dd bs=4096 count=1
      checking for mt... no
      checking if : is a manifest tool... no
      checking for dsymutil... dsymutil
      checking for nmedit... nmedit
      checking for lipo... lipo
      checking for otool... otool
      checking for otool64... no
      checking for -single_module linker flag... yes
      checking for -exported_symbols_list linker flag... yes
      checking for -force_load linker flag... yes
      checking for dlfcn.h... yes
      checking for objdir... .libs
      checking if gcc supports -fno-rtti -fno-exceptions... yes
      checking for gcc option to produce PIC... -fno-common -DPIC
      checking if gcc PIC flag -fno-common -DPIC works... yes
      checking if gcc static flag -static works... no
      checking if gcc supports -c -o file.o... yes
      checking if gcc supports -c -o file.o... (cached) yes
      checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
      checking dynamic linker characteristics... darwin21.5.0 dyld
      checking how to hardcode library paths into programs... immediate
      checking whether stripping libraries is possible... yes
      checking if libtool supports shared libraries... yes
      checking whether to build shared libraries... yes
      checking whether to build static libraries... no
      checking for inline... inline
      checking for gawk... (cached) awk
      checking for python... /opt/homebrew/opt/python@3.9/bin/python3.9
      checking for a version of Python >= '2.1.0'... yes
      checking for a version of Python >= '2.7'... yes
      checking for the distutils Python package... yes
      checking for Python include path... -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9
      checking for Python library path... -L/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib -lpython3.9
      checking for Python site-packages path... /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
      checking python extra libraries... -ldl   -framework CoreFoundation
      checking python extra linking flags... -Wl,-stack_size,1000000  -framework CoreFoundation /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Python
      checking consistency of all components of python development environment... yes
      checking for python version... 3.9
      checking for python platform... darwin
      checking for python script directory... ${prefix}/lib/python3.9/site-packages
      checking for python extension module directory... ${exec_prefix}/lib/python3.9/site-packages
      checking python3.9 module: sphinx... no
      checking python3.9 module: sphinx_rtd_theme... no
      checking for dbus-run-session... dbus-run-session
      checking for pkg-config... /opt/homebrew/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for dbus-1 >= 1.8... no
      configure: error: Package requirements (dbus-1 >= 1.8) were not met:
      
      No package 'dbus-1' found
      
      Consider adjusting the PKG_CONFIG_PATH environment variable if you
      installed software in a non-standard prefix.
      
      Alternatively, you may set the environment variables DBUS_CFLAGS
      and DBUS_LIBS to avoid the need to call pkg-config.
      See the pkg-config man page for more details.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/setup.py", line 85, in <module>
          setup(
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/setup.py", line 56, in run
          subprocess.check_call([
        File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/configure', '--disable-maintainer-mode', 'PYTHON=/opt/homebrew/opt/python@3.9/bin/python3.9', '--prefix=/private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/build/temp.macosx-12-arm64-cpython-39/prefix']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
  Building wheel for python-olm (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      /opt/homebrew/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      make: *** No rule to make target `../include/olm/olm.h', needed by `include/olm/olm.h'.  Stop.
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-cpython-39
      creating build/lib.macosx-12-arm64-cpython-39/olm
      copying olm/sas.py -> build/lib.macosx-12-arm64-cpython-39/olm
      copying olm/_finalize.py -> build/lib.macosx-12-arm64-cpython-39/olm
      copying olm/utility.py -> build/lib.macosx-12-arm64-cpython-39/olm
      copying olm/session.py -> build/lib.macosx-12-arm64-cpython-39/olm
      copying olm/__init__.py -> build/lib.macosx-12-arm64-cpython-39/olm
      copying olm/__version__.py -> build/lib.macosx-12-arm64-cpython-39/olm
      copying olm/group_session.py -> build/lib.macosx-12-arm64-cpython-39/olm
      copying olm/pk.py -> build/lib.macosx-12-arm64-cpython-39/olm
      copying olm/_compat.py -> build/lib.macosx-12-arm64-cpython-39/olm
      copying olm/account.py -> build/lib.macosx-12-arm64-cpython-39/olm
      running build_ext
      generating cffi module 'build/temp.macosx-12-arm64-cpython-39/_libolm.c'
      creating build/temp.macosx-12-arm64-cpython-39
      building '_libolm' extension
      creating build/temp.macosx-12-arm64-cpython-39/build
      creating build/temp.macosx-12-arm64-cpython-39/build/temp.macosx-12-arm64-cpython-39
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c build/temp.macosx-12-arm64-cpython-39/_libolm.c -o build/temp.macosx-12-arm64-cpython-39/build/temp.macosx-12-arm64-cpython-39/_libolm.o -I../include
      build/temp.macosx-12-arm64-cpython-39/_libolm.c:570:18: fatal error: 'olm/olm.h' file not found
              #include <olm/olm.h>
                       ^~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-olm
  Running setup.py clean for python-olm
Failed to build dbus-python python-olm
Installing collected packages: dbus-python, asyncio, argparse, aiofiles, zope.interface, zipp, unpaddedbase64, six, python-magic, pyrsistent, pycryptodome, pycparser, Pillow, multidict, idna, hyperframe, hpack, h11, future, frozenlist, charset-normalizer, cachetools, attrs, atomicwrites, async-timeout, yarl, jsonschema, importlib-metadata, h2, datetime, cffi, aiosignal, python-olm, markdown, aiohttp, aiohttp-socks, matrix-nio, matrix-commander
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Running setup.py install for dbus-python ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for dbus-python did not run successfully.
  │ exit code: 1
  ╰─> [164 lines of output]
      running install
      /opt/homebrew/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      creating /private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/build
      creating /private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/build/temp.macosx-12-arm64-cpython-39
      checking whether make supports nested variables... yes
      checking whether to enable maintainer-specific portions of Makefiles... no
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to accept ISO C89... none needed
      checking whether gcc understands -c and -o together... yes
      checking how to run the C preprocessor... gcc -E
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking minix/config.h usability... no
      checking minix/config.h presence... no
      checking for minix/config.h... no
      checking whether it is safe to define __EXTENSIONS__... yes
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a thread-safe mkdir -p... /private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/build-aux/install-sh -c -d
      checking for gawk... no
      checking for mawk... no
      checking for nawk... no
      checking for awk... awk
      checking whether make sets $(MAKE)... yes
      checking whether make supports the include directive... yes (GNU style)
      checking whether UID '501' is supported by ustar format... yes
      checking whether GID '20' is supported by ustar format... yes
      checking how to create a ustar tar archive... gnutar
      checking dependency style of gcc... gcc3
      checking build system type... arm-apple-darwin21.5.0
      checking host system type... arm-apple-darwin21.5.0
      checking for native Windows host... no
      checking how to print strings... printf
      checking for a sed that does not truncate output... /usr/bin/sed
      checking for fgrep... /usr/bin/grep -F
      checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
      checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
      checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
      checking the name lister (/usr/bin/nm -B) interface... BSD nm
      checking whether ln -s works... yes
      checking the maximum length of command line arguments... 786432
      checking how to convert arm-apple-darwin21.5.0 file names to arm-apple-darwin21.5.0 format... func_convert_file_noop
      checking how to convert arm-apple-darwin21.5.0 file names to toolchain format... func_convert_file_noop
      checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
      checking for objdump... objdump
      checking how to recognize dependent libraries... pass_all
      checking for dlltool... no
      checking how to associate runtime and link libraries... printf %s\n
      checking for ar... ar
      checking for archiver @FILE support... no
      checking for strip... strip
      checking for ranlib... ranlib
      checking command to parse /usr/bin/nm -B output from gcc object... ok
      checking for sysroot... no
      checking for a working dd... /bin/dd
      checking how to truncate binary pipes... /bin/dd bs=4096 count=1
      checking for mt... no
      checking if : is a manifest tool... no
      checking for dsymutil... dsymutil
      checking for nmedit... nmedit
      checking for lipo... lipo
      checking for otool... otool
      checking for otool64... no
      checking for -single_module linker flag... yes
      checking for -exported_symbols_list linker flag... yes
      checking for -force_load linker flag... yes
      checking for dlfcn.h... yes
      checking for objdir... .libs
      checking if gcc supports -fno-rtti -fno-exceptions... yes
      checking for gcc option to produce PIC... -fno-common -DPIC
      checking if gcc PIC flag -fno-common -DPIC works... yes
      checking if gcc static flag -static works... no
      checking if gcc supports -c -o file.o... yes
      checking if gcc supports -c -o file.o... (cached) yes
      checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
      checking dynamic linker characteristics... darwin21.5.0 dyld
      checking how to hardcode library paths into programs... immediate
      checking whether stripping libraries is possible... yes
      checking if libtool supports shared libraries... yes
      checking whether to build shared libraries... yes
      checking whether to build static libraries... no
      checking for inline... inline
      checking for gawk... (cached) awk
      checking for python... /opt/homebrew/opt/python@3.9/bin/python3.9
      checking for a version of Python >= '2.1.0'... yes
      checking for a version of Python >= '2.7'... yes
      checking for the distutils Python package... yes
      checking for Python include path... -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9
      checking for Python library path... -L/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib -lpython3.9
      checking for Python site-packages path... /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
      checking python extra libraries... -ldl   -framework CoreFoundation
      checking python extra linking flags... -Wl,-stack_size,1000000  -framework CoreFoundation /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Python
      checking consistency of all components of python development environment... yes
      checking for python version... 3.9
      checking for python platform... darwin
      checking for python script directory... ${prefix}/lib/python3.9/site-packages
      checking for python extension module directory... ${exec_prefix}/lib/python3.9/site-packages
      checking python3.9 module: sphinx... no
      checking python3.9 module: sphinx_rtd_theme... no
      checking for dbus-run-session... dbus-run-session
      checking for pkg-config... /opt/homebrew/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for dbus-1 >= 1.8... no
      configure: error: Package requirements (dbus-1 >= 1.8) were not met:
      
      No package 'dbus-1' found
      
      Consider adjusting the PKG_CONFIG_PATH environment variable if you
      installed software in a non-standard prefix.
      
      Alternatively, you may set the environment variables DBUS_CFLAGS
      and DBUS_LIBS to avoid the need to call pkg-config.
      See the pkg-config man page for more details.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/setup.py", line 85, in <module>
          setup(
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 670, in run
          self.run_command('build')
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/setup.py", line 56, in run
          subprocess.check_call([
        File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/configure', '--disable-maintainer-mode', 'PYTHON=/opt/homebrew/opt/python@3.9/bin/python3.9', '--prefix=/private/var/folders/3k/j_by2bw56jd5w_ss9c8qr3kc0000gn/T/pip-install-c4n3xeqr/dbus-python_26a5ad4fc6de47f9b8dbb58979ee10f0/build/temp.macosx-12-arm64-cpython-39/prefix']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dbus-python

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
</details>

**Comment by KizzyCode** [comment]
Update – I was able to successfully install matrix-commander using the following steps:
 - Install `libolm`, `dbus` and `libmagic` using Homebrew
 - Install `matrix-commander` using
   ```
   pip3 install --global-option=build_ext --global-option="-I/opt/homebrew/include/" --global-option="-L/opt/homebrew/lib/" matrix-commander
   ```
   (this seems to be necessary, because Homebrew on M1 is located within `/opt/homebrew` which breaks default include and link paths)

Maybe this can be included in `PyPi-Instructions.md`? 😊

**Comment by 8go** [comment]
:clap: :clap: :clap: Thank you @KizzyCode for this contribution ! 

Your instructions are online at https://pypi.org/project/matrix-commander/ now!
