### ISSUE TITLE
Does not work because of missing dbus

### ISSUE THREAD

**Issue by frankgerhardt** [8go/matrix-commander#9]
```
matrix-commander$ pip install -r requirements.txt
Collecting aiofiles<0.5.0,>=0.4.0
  Using cached aiofiles-0.4.0-py3-none-any.whl (9.2 kB)
Collecting matrix-nio[e2e]>=0.14.1
  Downloading matrix_nio-0.15.2-py3-none-any.whl (173 kB)
     |████████████████████████████████| 173 kB 5.2 MB/s 
Collecting aiohttp
  Downloading aiohttp-3.7.3-cp38-cp38-manylinux2014_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 7.4 MB/s 
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting atomicwrites<2.0.0,>=1.3.0
  Downloading atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting attrs>=17.3.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 4.4 MB/s 
Collecting cachetools<5.0.0,>=4.0.0
  Downloading cachetools-4.2.0-py3-none-any.whl (12 kB)
Collecting chardet<4.0,>=2.0
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting future<0.19.0,>=0.18.2
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting h11<0.10.0,>=0.9.0
  Using cached h11-0.9.0-py2.py3-none-any.whl (53 kB)
Collecting h2<4.0.0,>=3.2.0
  Using cached h2-3.2.0-py2.py3-none-any.whl (65 kB)
Collecting hpack<4,>=3.0
  Using cached hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Collecting hyperframe<6,>=5.2.0
  Using cached hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Collecting jsonschema<4.0.0,>=3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Requirement already satisfied: setuptools in /home/siena/bin/anaconda3/envs/py38env/lib/python3.8/site-packages (from jsonschema<4.0.0,>=3.2.0->matrix-nio[e2e]>=0.14.1->-r requirements.txt (line 7)) (51.0.0.post20201207)
Collecting logbook<2.0.0,>=1.5.3
  Using cached Logbook-1.5.3.tar.gz (85 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-5.1.0-cp38-cp38-manylinux2014_x86_64.whl (159 kB)
     |████████████████████████████████| 159 kB 5.3 MB/s 
Collecting peewee<4.0.0,>=3.13.2
  Downloading peewee-3.14.0.tar.gz (873 kB)
     |████████████████████████████████| 873 kB 4.9 MB/s 
Collecting pycryptodome<4.0.0,>=3.9.7
  Downloading pycryptodome-3.9.9-cp38-cp38-manylinux1_x86_64.whl (13.7 MB)
     |████████████████████████████████| 13.7 MB 8.4 MB/s 
Collecting pyrsistent>=0.14.0
  Downloading pyrsistent-0.17.3.tar.gz (106 kB)
     |████████████████████████████████| 106 kB 8.0 MB/s 
Collecting python-olm<4.0.0,>=3.1.3
  Using cached python-olm-3.1.3.tar.gz (27 kB)
Collecting cffi>=1.0.0
  Using cached cffi-1.14.4-cp38-cp38-manylinux1_x86_64.whl (411 kB)
Collecting six>=1.11.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting typing-extensions>=3.6.5
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting unpaddedbase64<2.0.0,>=1.1.0
  Using cached unpaddedbase64-1.1.0-py2.py3-none-any.whl (3.3 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.6.3-cp38-cp38-manylinux2014_x86_64.whl (324 kB)
     |████████████████████████████████| 324 kB 6.8 MB/s 
Collecting idna>=2.0
  Downloading idna-3.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 4.7 MB/s 
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting asyncio
  Downloading asyncio-3.4.3-py3-none-any.whl (101 kB)
     |████████████████████████████████| 101 kB 5.7 MB/s 
Collecting datetime
  Downloading DateTime-4.3-py2.py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 4.8 MB/s 
Collecting markdown
  Downloading Markdown-3.3.3-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 4.2 MB/s 
Collecting notify2
  Downloading notify2-0.3.1-py2.py3-none-any.whl (8.0 kB)
Collecting Pillow
  Downloading Pillow-8.1.0-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 6.8 MB/s 
Collecting python_magic
  Downloading python_magic-0.4.18-py2.py3-none-any.whl (8.6 kB)
Collecting uuid
  Downloading uuid-1.30.tar.gz (5.8 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pytz
  Downloading pytz-2020.5-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 7.7 MB/s 
Collecting zope.interface
  Downloading zope.interface-5.2.0-cp38-cp38-manylinux2010_x86_64.whl (244 kB)
     |████████████████████████████████| 244 kB 6.5 MB/s 
Building wheels for collected packages: future, logbook, peewee, pyrsistent, python-olm, uuid
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=76679b2f53206c03b761b36af5fb418ef06c3a8ec5e4aa3aab7887ee08b7b1be
  Stored in directory: /home/siena/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
  Building wheel for logbook (setup.py) ... done
  Created wheel for logbook: filename=Logbook-1.5.3-cp38-cp38-linux_x86_64.whl size=66378 sha256=65c69a9b36bf99a83a6b9a51e1208082da44c922dc0271537a12e010e1bfdd29
  Stored in directory: /home/siena/.cache/pip/wheels/25/9a/c0/03bf368ac5f673e9c0bde58837146b004424b25555ca3aedfb
  Building wheel for peewee (setup.py) ... done
  Created wheel for peewee: filename=peewee-3.14.0-py3-none-any.whl size=128142 sha256=54d73d0edafa5c87c52ea97667c9873ac63c9a66ce4e6d75e6054d8766ecdfce
  Stored in directory: /home/siena/.cache/pip/wheels/f9/0c/4f/37984c77779105edbafffd114ac40820bfa4f1f1bf9ff6ed57
  Building wheel for pyrsistent (setup.py) ... done
  Created wheel for pyrsistent: filename=pyrsistent-0.17.3-cp38-cp38-linux_x86_64.whl size=126087 sha256=4e37bdd619298fcb183580f5f0c3b4786a9771188d053fbe51de3af54c67087f
  Stored in directory: /home/siena/.cache/pip/wheels/3d/22/08/7042eb6309c650c7b53615d5df5cc61f1ea9680e7edd3a08d2
  Building wheel for python-olm (setup.py) ... done
  Created wheel for python-olm: filename=python_olm-3.1.3-cp38-cp38-linux_x86_64.whl size=160910 sha256=9ed2a082eaaf13554f1e975a4819ffae051b75daa5792d5fbf612b5570669803
  Stored in directory: /home/siena/.cache/pip/wheels/1c/a0/53/ea4c79f60693fcef0951216bb94ee25545632e686403fbb438
  Building wheel for uuid (setup.py) ... done
  Created wheel for uuid: filename=uuid-1.30-py3-none-any.whl size=6501 sha256=4f57c5c65e4d923d04a1b6b883d0c9d77f1054ba0d09387332e5dfdeb0886096
  Stored in directory: /home/siena/.cache/pip/wheels/1b/6c/cb/f9aae2bc97333c3d6e060826c1ee9e44e46306a178e5783505
Successfully built future logbook peewee pyrsistent python-olm uuid
Installing collected packages: multidict, idna, yarl, typing-extensions, six, pyrsistent, pycparser, hyperframe, hpack, chardet, attrs, async-timeout, unpaddedbase64, pycryptodome, logbook, jsonschema, h2, h11, future, cffi, aiohttp, aiofiles, zope.interface, pytz, python-olm, peewee, matrix-nio, cachetools, atomicwrites, uuid, python-magic, Pillow, notify2, markdown, datetime, asyncio, argparse
Successfully installed Pillow-8.1.0 aiofiles-0.4.0 aiohttp-3.7.3 argparse-1.4.0 async-timeout-3.0.1 asyncio-3.4.3 atomicwrites-1.4.0 attrs-20.3.0 cachetools-4.2.0 cffi-1.14.4 chardet-3.0.4 datetime-4.3 future-0.18.2 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hyperframe-5.2.0 idna-3.0 jsonschema-3.2.0 logbook-1.5.3 markdown-3.3.3 matrix-nio-0.15.2 multidict-5.1.0 notify2-0.3.1 peewee-3.14.0 pycparser-2.20 pycryptodome-3.9.9 pyrsistent-0.17.3 python-magic-0.4.18 python-olm-3.1.3 pytz-2020.5 six-1.15.0 typing-extensions-3.7.4.3 unpaddedbase64-1.1.0 uuid-1.30 yarl-1.6.3 zope.interface-5.2.0
```

After installing all requirements it does not work:

```
matrix-commander$ ./matrix-commander.py 
Traceback (most recent call last):
  File "./matrix-commander.py", line 508, in <module>
    import notify2
  File "/home/siena/bin/anaconda3/envs/py38env/lib/python3.8/site-packages/notify2.py", line 39, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

**Comment by vlp-git** [comment]
Did you install:
    pip3 install dbus-python ?

**Comment by 8go** [comment]
@frankgerhardt Thanks for pointing out this shortcoming.

@vlp-git Thanks for providing the solution.

I updated the `requirements.txt` file and the comments in `README.md`. 

Closing issue now, thank to you both again! Cheers!

**Comment by 8go** [comment]
There was a lovely contribution from @fyfe in PR #12 
This helps you! Looks like @fyfe made it tailor-made for you!
No longer is installation of notify2 required. No need to install dbus-python either.
Thanks to @fyfe it all works now also without notify and dbus-python installed.
